using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Fumo.EditorWasm.Generator
{
    /// <summary>
    /// Generates a registry of host API surface area (xLua Generator pattern).
    /// </summary>
    public static class HostBindingGenerator
    {
        const string OutputRelative = "Generated/EditorHostApiRegistry.g.cs";

        public static void Generate()
        {
            var packageRoot = FindPackageRoot();
            var outputPath = Path.Combine(packageRoot, OutputRelative);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? packageRoot);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Fumo.EditorWasm.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EditorHostApiRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IReadOnlyList<string> ApiTypes => _apiTypes;");
            sb.AppendLine("        static readonly string[] _apiTypes = new string[]");
            sb.AppendLine("        {");

            var apiTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(SafeGetTypes)
                .Where(t => t.IsDefined(typeof(EditorHostApiAttribute), inherit: false))
                .Select(t => t.FullName)
                .Distinct()
                .OrderBy(n => n)
                .ToList();

            if (apiTypes.Count == 0)
                sb.AppendLine("            // Add [EditorHostApi] to types and [EditorHostGenConfig] to a config class.");
            else
                foreach (var name in apiTypes)
                    sb.AppendLine($"            \"{name}\",");

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(outputPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[WasmEditor] Generated host API registry at {outputPath}");
        }

        static string FindPackageRoot()
        {
            var guids = AssetDatabase.FindAssets("Fumo.EditorWasm asmdef");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.EndsWith("Fumo.EditorWasm.asmdef"))
                    return Path.GetDirectoryName(Path.GetDirectoryName(path));
            }

            return Path.Combine(Directory.GetParent(Application.dataPath)?.FullName ?? ".", "Packages", "com.fumo.editor-wasm");
        }

        static Type[] SafeGetTypes(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                return ex.Types.Where(t => t != null).ToArray();
            }
        }
    }
}
