using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Fumo.EditorWasm.Generator
{
    /// <summary>
    /// Generates HostImportRegistry.g.cs from schemas/host-imports.v1.json.
    /// </summary>
    public static class HostImportRegistryGenerator
    {
        const string ManifestRelative = "schemas/host-imports.v1.json";
        const string OutputRelative = "Generated/HostImportRegistry.g.cs";

        [Serializable]
        class ManifestRoot
        {
            public string abi;
            public ImportEntry[] imports;
            public string[] exports;
        }

        [Serializable]
        class ImportEntry
        {
            public string module;
            public string name;
            public int tier;
        }

        public static void Generate()
        {
            var packageRoot = HostBindingGenerator.FindPackageRoot();
            var manifestPath = ResolveManifestPath(packageRoot);
            if (!File.Exists(manifestPath))
                throw new FileNotFoundException($"Host import manifest not found: {manifestPath}");

            var json = File.ReadAllText(manifestPath);
            var manifest = JsonUtility.FromJson<ManifestRoot>(json);
            if (manifest?.imports == null || manifest.imports.Length == 0)
                throw new InvalidOperationException("host-imports manifest has no imports.");

            var outputPath = Path.Combine(packageRoot, OutputRelative);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? packageRoot);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated from schemas/host-imports.v1.json via HostImportRegistryGenerator />");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Fumo.EditorWasm.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class HostImportRegistry");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string Abi = \"{manifest.abi}\";");
            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<HostImportEntry> Imports => _imports;");
            sb.AppendLine("        public static IReadOnlyList<string> RequiredExports => _exports;");
            sb.AppendLine();
            sb.AppendLine("        static readonly HostImportEntry[] _imports =");
            sb.AppendLine("        {");

            foreach (var entry in manifest.imports.OrderBy(i => i.tier).ThenBy(i => i.module).ThenBy(i => i.name))
                sb.AppendLine($"            new(\"{entry.module}\", \"{entry.name}\", {entry.tier}),");

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        static readonly string[] _exports =");
            sb.AppendLine("        {");
            foreach (var export in manifest.exports ?? Array.Empty<string>())
                sb.AppendLine($"            \"{export}\",");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public readonly struct HostImportEntry");
            sb.AppendLine("    {");
            sb.AppendLine("        public HostImportEntry(string module, string name, int tier)");
            sb.AppendLine("        {");
            sb.AppendLine("            Module = module;");
            sb.AppendLine("            Name = name;");
            sb.AppendLine("            Tier = tier;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public string Module { get; }");
            sb.AppendLine("        public string Name { get; }");
            sb.AppendLine("        public int Tier { get; }");
            sb.AppendLine("        public string Key => $\"{Module}.{Name}\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(outputPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[WasmEditor] Generated host import registry at {outputPath}");
        }

        public static string ResolveManifestPath(string packageRoot)
        {
            var repoRoot = Path.GetFullPath(Path.Combine(packageRoot, "..", ".."));
            var repoManifest = Path.Combine(repoRoot, ManifestRelative);
            if (File.Exists(repoManifest))
                return repoManifest;

            var projectRoot = Directory.GetParent(Application.dataPath)?.FullName;
            if (!string.IsNullOrEmpty(projectRoot))
            {
                var projectManifest = Path.Combine(projectRoot, "..", ManifestRelative);
                if (File.Exists(projectManifest))
                    return Path.GetFullPath(projectManifest);
            }

            return repoManifest;
        }
    }
}
