// <auto-generated from schemas/host-imports.v1.json>
// Run: python3 scripts/gen-rust-imports.py [output]

#[link(wasm_import_module = "editor_assets")]
extern "C" {
    pub fn asset_exists(_0: i32, _1: i32) -> i32;
    pub fn find_asset_at(_0: i32, _1: i32, _2: i32, _3: i32, _4: i32, _5: i32, _6: i32) -> i32;
    pub fn find_assets_count(_0: i32, _1: i32, _2: i32, _3: i32) -> i32;
    pub fn load_text_asset(_0: i32, _1: i32, _2: i32, _3: i32) -> i32;
    pub fn write_bulk_payload(_0: i32, _1: i32, _2: i32, _3: i32) -> i32;
}

#[link(wasm_import_module = "editor_core")]
extern "C" {
    pub fn clear_progress();
    pub fn get_editor_time() -> f64;
    pub fn log(_0: i32, _1: i32, _2: i32);
    pub fn log_error(_0: i32, _1: i32);
    pub fn show_progress(_0: i32, _1: i32, _2: i32, _3: i32, _4: f32);
}

#[link(wasm_import_module = "editor_scene")]
extern "C" {
    pub fn get_component_count(_0: i64) -> i32;
    pub fn get_component_type_at(_0: i64, _1: i32, _2: i32, _3: i32) -> i32;
    pub fn get_object_path(_0: i64, _1: i32, _2: i32) -> i32;
    pub fn get_serialized_property(_0: i64, _1: i32, _2: i32, _3: i32, _4: i32) -> i32;
}

#[link(wasm_import_module = "editor_selection")]
extern "C" {
    pub fn get_active_asset_path(_0: i32, _1: i32) -> i32;
    pub fn get_active_object() -> i64;
    pub fn get_active_object_at(_0: i32) -> i64;
    pub fn get_active_objects_count() -> i32;
    pub fn get_object_name(_0: i64, _1: i32, _2: i32) -> i32;
}
