#!/usr/bin/env python3
"""Generate Rust extern import blocks from schemas/host-imports.v1.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

RUST_TYPE = {
    "i32": "i32",
    "i64": "i64",
    "f32": "f32",
    "f64": "f64",
}


def format_fn(entry: dict) -> str:
    params = entry.get("params") or []
    returns = entry.get("returns") or []
    args = ", ".join(f"_{i}: {RUST_TYPE[t]}" for i, t in enumerate(params))
    ret = " -> " + RUST_TYPE[returns[0]] if len(returns) == 1 else ""
    return f"    pub fn {entry['name']}({args}){ret};"


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    manifest_path = root / "schemas" / "host-imports.v1.json"
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else None

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    modules: dict[str, list[dict]] = {}
    for entry in manifest["imports"]:
        modules.setdefault(entry["module"], []).append(entry)

    lines = [
        "// <auto-generated from schemas/host-imports.v1.json>",
        "// Run: python3 scripts/gen-rust-imports.py [output]",
        "",
    ]

    for module, entries in sorted(modules.items()):
        lines.append(f'#[link(wasm_import_module = "{module}")]')
        lines.append('extern "C" {')
        for entry in sorted(entries, key=lambda e: e["name"]):
            lines.append(format_fn(entry))
        lines.append("}")
        lines.append("")

    output = "\n".join(lines).rstrip() + "\n"
    if out_path:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
        print(f"Wrote {out_path}")
    else:
        sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
